services:
  backend:
    build:
      context: ./backend
    container_name: mastercard_dashboard_backend
    environment:
      PORT: ${PORT:-4000}
      AWS_REGION: ${AWS_REGION:-us-west-2}
      LAMBDA_FUNCTION_NAME: ${LAMBDA_FUNCTION_NAME:-mastercard-aurora-proxy}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5273}
    volumes:
      - ./backend/src:/app/src
    command: npm run dev
    ports:
      - "${BACKEND_PORT:-4100}:4000"

  frontend:
    build:
      context: ./frontend
    container_name: mastercard_dashboard_frontend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:4100}
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "${FRONTEND_PORT:-5273}:5173"
    depends_on:
      - backend
